### ISSUE TITLE
Difference between `get` and `getLong`

### ISSUE THREAD

**Issue by DanielSWolf** [js-joda/js-joda#102]
Various js-joda classes offer both a `get` and a `getLong` method. Now I'm a bit confused.

First I thought that `getLong` was merely a relict from Java, where some values may not fit into a 32-bit `int`, but do fit into a 64-bit `long`. This seemed to be confirmed by classes like `Instant` and `ZonedDateTime`, where `get` merely calls `getLong`.

But then I found `DayOfWeek`, where `get` and `getLong` seem to do almost the same thing, but differ in exception handling. And `LocalDateTime`, where the two methods are implemented completely differently. Which I find rather surprising.

So what's the idea behind having these two methods?

**Comment by phueper** [comment]
Hi @DanielSWolf,

thanks for reporting this issue, also, see my comment on #103  :) 

These methods don't make much sense from a JS Point of view and we plan to merge them in the future https://github.com/js-joda/js-joda#future-milestones ... our focus for now was to port the library as it is. And as you said sometimes the `get()` and `getLong()` implementations are very similar and sometimes they are not.. as a rule of thumb i think it makes more sense to use the `get()` functions, since the `getLong()` will maybe go away in the future.

Regards, Pattrick

**Comment by pithu** [comment]
As get and getLong should be similar for all classes in javascript, we would appreciate a pull request that is merging all occurrences of get and getLong into, lets say, getNumber.

**Comment by DanielSWolf** [comment]
Thanks!

**Comment by DanielSWolf** [comment]
I agree that merging `get` and `getLong` makes sense. Regarding the name: I'd simply call it `get`. First, that's in line with joda time; second, `date.get(ChronoField.DAY_OF_YEAR)` reads nicely.

**Comment by pithu** [comment]
`get` sounds good, better then `getNumber`. 

BTW there is a `LocalDate.dayOfYear()` method.
