### ISSUE TITLE
Missing Interval aka Range Calculation

### ISSUE THREAD

**Issue by chauthai** [js-joda/js-joda#109]
Hi,

I noticed `js-joda` is missing the [Interval Class](http://joda-time.sourceforge.net/apidocs/org/joda/time/Interval.html) from the orginal `joda-time` implementation.
Is there any ETA for it? We are using [moment-range](https://github.com/gf3/moment-range) for overlap calculation, but we want switch to `js-joda` as soon as possible.

**Comment by pithu** [comment]
Hello @chauthai, 

js-joda is not a port of joda-time but of the threeten backport project from Stephen Colebourne (the author of joda-time). threeten is "inspired by Joda-Time", rather than an exact derivation, however many concepts will be familiar.

At this blog article http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html find a good overview about joda-time vs. threeten. threeten is neither java.time nor JSR310 but has the same API, find more Information here -> http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html

**The Interval class is not included in threeten and therefore it will be not part of js-joda.** 

The Intervall class is part of the threeten extra package, that contains stuff that not ended up in JSR310. We are open for a js-joda-extra project, porting threeten-extra to javascript, but we have no plans to work on that by ourself. js-joda is plug-able, a package like that could be easily added like that `{Interval} = require('js-joda').use(require('js-joda-extra'))`

**Comment by phueper** [comment]
Hello @chauthai 

First of all, thank you for planning to use `js-joda` :) We are happy to hear that you want to use it.

As @pithu said, `js-joda` is a port of the threetenbp project and since the `Interval` class is not part of threetenbp, it will not be added to js-joda.

Having said that, we want `js-joda` to be pluggable and extendable, and since i can see the value of the classes that existed in joda-time but are not part of threetenbp (and since the author of threetenbp and JSR-310 also provides them in https://github.com/ThreeTen/threeten-extra), i started a new repo to have a place for the classes that are part of threeten-extra: 

https://github.com/js-joda/js-joda-extra

Now, this is currently very incomplete (actually it *only* consists of the `Interval` class and tests for it, and even that is currently missing the `parse()` function), but i think it could be a starting point to port more of the threeten-extra classes. I will probably not have much time to do that in the near future, but we are happy to consider Pull Requests that add additional classes from the threeten-extra project.

It is rather quickly strung together, lots of copy and paste from the js-joda (core) repo, but i think it should basically work, if you want to test it i'd be happy, please report issues (or success :)) with it in that repository ... https://github.com/js-joda/js-joda-extra/issues

I will close this issue now, since it does not relate to js-joda and would be happy to discuss anything else related to it in js-joda-extra. See you there ;)

Regards, Pattrick
