### ISSUE TITLE
Add method withResolverStyle to DateTimeFormatter

### ISSUE THREAD

**Issue by asfernandes** [js-joda/js-joda#131]
Please add this method present in Java's Joda.

I can't construct a formatter (parser) in strict mode using TypeScript.

**Comment by phueper** [comment]
Hi @asfernandes 

First of all thanks for using js-joda and thanks for your issue report... 

Could you give us a little more information and ideally a code example of what you are trying to do and what you expect to happen? That would be really helpful for us to see if and how we can implement this.

Just a word of warning, if it has anything to do with locales and locale specific dates, we currently do not support locales yet, that would be something that is on our roadmap.

But since we ported the ResolverStyle already and also use it, it might be possible to implement `withResolverStyle` or provide you with a workaround, but that depends on your usecase.

Regards, Pattrick

**Comment by asfernandes** [comment]
It's not about locale.

I created a formatter with `DateTimeFormatter.ofPattern('dd/MM/yyyy')`.

With this formatter, I do `LocalDate.parse(str, dateFormatter)`.

The problem is that this parses invalid dates - 31/04/2017 (april) or 31/02/2017 (february) - to the month's last day. Accordingly to the Java documentation, using a strict resolver avoids this.

**Comment by pithu** [comment]
I found this on stack overflow. http://stackoverflow.com/questions/37125709/how-to-do-strict-localdate-parsing-in-js-joda.

It looks like there is a workaround for creating a DateTimeFormatter with a certain ResolverStyle.
And you have to replace patter `yyyy` by `uuuu`.

```
dateFormatter = new DateTimeFormatterBuilder()
     .appendPattern('dd/MM/uuuu')
     .toFormatter(ResolverStyle.STRICT)

LocalDate.parse('31/04/2017', dateFormatter) // fails
LocalDate.parse('30/04/2017', dateFormatter) // worx
```

**Comment by phueper** [comment]
@asfernandes  could you try if the workaround @pithu provided works for you? 

And i will see that we get `withResolverStyle` implemented/tested and into one of our next releases

**Comment by pithu** [comment]
@phueper and as stated in the stack overflow issue our API Doc is incomplete. The pattern `u` is missing in the docs.

**Comment by phueper** [comment]
@pithu ... ok, thx, i will check and update that too

**Comment by asfernandes** [comment]
Yes, the workaround worked for me. Thanks!

However, I need to call `new DateTimeFormatterBuilder(null, false)` in TypeScript, and accordingly to the documentation of DateTimeFormatterBuilder that would be invalid: "the parent builder, not null".

The documentations seems to not follow the code too. Nor does the TypeScript mapping.

```
constructor(parent=null, optional=false)
```

**Comment by pithu** [comment]
👍 

Another thing: we could implement the _private_ constructor of the `DateTimeFormatterBuilder` as a static _private_ factory e.g. `_of(...)`. So the description do not appear in the esdoc anymore. And there might be more cases in the code base where we have a wrong/ confusing doc because of private constructors.

**Comment by phueper** [comment]
@pithu 👍 should we create a separate issue for that? It doesn't make sense in the context of this issue imho?
