### ISSUE TITLE
Why does ZonedDataTime have both _offset and _zone?

### ISSUE THREAD

**Issue by memelet** [js-joda/js-joda#139]
I have initialized with
```
import * as joda from 'js-joda'
import jstz from 'js-joda-timezone'
joda.use(jstz)
```

Then create a ZonedDataTime
```
const zdt = joda.ZonedDateTime.now(joda.ZoneId.UTC)
```

This `zdt` object has both an `_offset` and `_zone`, which are identical and both of the type `ZoneOffset`.

**Comment by pithu** [comment]
Hi @memelet,

First of all thanks for using js-joda and thanks for your issue report...

As you probably now, but just to make it clear: All properties in js-joda starting with `_` are meant to be `private` and `immutable`. You should **NEVER** read **NOR** write this properties.

And yes, that is correct, for ZonedDateTime instances with a `Fixed` ZoneOffset the values `_offset` and `_zone` are equal and sharing the same reference. If you just working with Fixed offsets (like UTC, GMT, etc) you do not require the `js-joda-timezone` plugin at all. Depending on your use case you might consider to use LocalDateTime instead of ZonedDateTime.

If you are using ZonedDateTime together with a ZoneRegion you need the `js-joda-timezone` plugin and the `_offset` property holds the current offset for the current daylight saving transition and the `_zone` property holds the ZoneRegion. For example:

```
const zdt = LocalDate.parse('2012-06-06').atStartOfDay().atZone(ZoneId.of('Europe/Paris'))
// offset is +02:00, zone is 'Europe/Paris'
```

I hope that answers your question.

**Comment by memelet** [comment]
Yes, that's very clear. I've been studying up and ran across the distinction between zone and offset.

I'm an old joda-time user that is so very happy to have js-joda for javascript, so I thank you very much.
