### ISSUE TITLE
ZoneId and subclasses to not implement toString or toJSON fully

### ISSUE THREAD

**Issue by memelet** [js-joda/js-joda#144]
This is related to #143 I think, where again I have problems with timezone rendering. With bunyan any object that contains a ZoneId with js-joda-timezone enabled will fail to render due to cycles, eg:
```
 timezone: 
   ZoneOffset {
     _totalSeconds: 0,
     _rules: Fixed { _offset: [Circular] },
     _id: 'Z' },
```

In #143 it was mentioned all js-joda classes implement `toString()` and `toJSON()`, but it seems this is not fully case. `ZoneId` delegates its `toString()`:
```
toString() {
  return this.id();
}
```
And subclasses ZoneId do not all implement toString or toJSON like `ZoneRegion` and `SystemDefaultZoneId` and `ZoneOffset`. 

Its this I think that was causing the issues in #143 and also causing problems when logging.

Should these classes implement at least `toString`?

**Comment by pithu** [comment]
Hello @memelet 

All js-joda classes implement `toString`. Some of them delegating toString to the super class, that's by purpose and correct.

`toJSON` is implemented for the most classes where its useful, like where the the output is parsable again.  We missed that for some classes like ZoneId and ZoneRegion. Thanks for reporting.
I added this method already and you will find that in the next release. 

And yes `ZoneId's` with a `Fixed` offset containing a self reference. `JSON.stringify` will fail on a Fixed ZoneOffset for now. That will be fIxed by the `toJSON` method with the next release.

**Comment by pithu** [comment]
Hello @memelet find the missong toJSON method in the latest release version v1.5.0
