### ISSUE TITLE
Timezone ambiguity

### ISSUE THREAD

**Issue by dcosson** [js-joda/js-joda#165]
I'm not familiar with the Java API that js-joda is based on, but it seems like there's an unfortunate ambiguity in timezone handling (though js-joda is definitely better than native JS Date or moment at this).

From the docs - `ZonedDateTime is a date-time with a time-zone in the ISO-8601 calendar system, such as 2007-12-24T16:15:30+01:00 UTC+01:00.`

But it's actually a UTC offset which is different than a timezone. The obvious difference is at daylight savings boundaries:

```
JSJoda.ZonedDateTime.parse("2017-03-12T01:00:00-08:00[America/Los_Angeles]").plusHours(3).toJSON()
"2017-03-12T05:00-07:00[America/Los_Angeles]"
JSJoda.ZonedDateTime.parse("2017-03-12T01:00:00-08:00").plusHours(3).toJSON()
"2017-03-12T04:00-08:00"
```

It looks like Joda represents these as using `Fixed` zone rules for the offset case and `MomentZoneRules` for the Timezone case. Because this difference so frequently leads to timezone related bugs, it would be nice if these were completely separate types such as a `ZonedDateTime` and a `ZoneOffsetDateTime`.

To be really strict and avoid ambiguity, ZoneOffset datetimes ideally wouldn't even support time duration operations like plusSeconds or plusHours (you could always convert to an Instant in UTC, addSeconds, and then convert back if you really wanted to but that seems like it's pretty much never actually what you want).

It would obviously be a breaking change, but would that be at all feasible to implement?

**Comment by pithu** [comment]
Hello @dcosson,

First of all, js-joda is a port of the threeten API, that is a backport of JSR-310/java.time API. We are pretty strict to follow the API of our upstream project and will not accept any changes/enhancements to that API.

The threeten API (and therefore js-joda) knows two different implementations of a timezone id (called `ZoneId` in threeten). A ZoneId is either a fixed offset from UTC (called `ZoneOffset`) or a geographical region  called `ZoneRegion` with specific set of rules provided by IANA for finding the right offset from UTC.

A `ZonedDateTime` is a composition of a `LocalDateTime`, a `ZoneID` and a resolved `ZoneOffset` and can handle fixed offsets and zone regions. 

With a fixed offset a ZonedDateTime behaves like an `OffsetDateTime`. That is probably what you miss in js-joda. The domain `OffsetDateTime` exists in the threeten API but is not yet implemented in js-joda. A `OffsetDateTime` is a composition of a LocalDateTime and a ZoneOffset. Actually we have no plans to migrate `OffsetDateTime` to js-joda, (because the functionality is allready covered by `ZonedDateTime`), but since it is part of the threeten API we would accept a PR for that.
    
Regarding time based operations for a ZonedDateTime i disagree. What is the purpose of a ZonedDateTime without the possibility to perform time based operations? 

Does this answer remove ambiguity a bit ?

**Comment by dcosson** [comment]
Thanks for the detailed response. This makes sense, I didn't realize Threeten was such a formalized API.

I think what I missed is that in the Threeten api the offsets themselves are valid ZoneId's (for better or worse).

From my reading of the docs, it does seem like `ZoneDateTime.parse` as implemented in js-joda might be incorrect? The docs say it should parse the [ISO_ZONED_DATE_TIME](http://www.threeten.org/threetenbp/apidocs/org/threeten/bp/format/DateTimeFormatter.html#ISO_ZONED_DATE_TIME) format, and that format explicitly requires a ZoneID between brackets.  My reading is that formats like  `2011-12-03T10:15:30+01:00[Europe/Paris]` and `2011-12-03T10:15:30+01:00[UTC+1]` would both be valid, but `2011-12-03T10:15:30+01:00` is actually incomplete.

In my experience, requiring explicitly setting the zone like this would be very helpful in preventing subtle timezone bugs.

It also says "If the zone ID is not available or is a ZoneOffset then the format is complete", which to me means something like `2011-12-03T10:15:30+01:00[UTC+1]` might actually be invalid but it could also mean that it needs the "UTC" part in the zoneId rather than just the offset. 🤷‍♂️

**Comment by dcosson** [comment]
Update: I was curious so I tried out the java library:

```
jshell> import java.time.ZonedDateTime

jshell> ZonedDateTime.parse("2017-11-05T01:00:00-07:00").getZone()
$1 ==> -07:00
```

It looks like it does allow not passing in an explicit ZoneId, despite the wording in the docs.

Thanks again for the clarification. It would be cool to still support OffsetDateTime, if I get a chance I'll try to implement it.
