### ISSUE TITLE
to freeze or not to freeze ?

### ISSUE THREAD

**Issue by pithu** [js-joda/js-joda#19]
We are thinking about freezing the js-joda classes and instances with Object.freeze(). 

We could freeze only the class itself and there static instances like LocalTime.MIDNIGHT, so it is not possible to manipulate constant values by mistake (making bad things such as LocalTime.MIDNIGHT._hour = 24 impossible). I made some benchmark tests at https://github.com/pithu/js-joda/blob/benchmark/benchmark.js. For the v8 and the latest browsers like Chrome, Firefox, Safari, Edge it seems to have no impact on performance to freeze just the static class properties. 

And we could even freeze all returned instances by js-joda.  But this would have a big impact on performance. The Object.freeze operation itself is slow in all browser. In Chrome reading properties of a frozen object is faster, then reading from normal object. But in other browsers reading seems to be much slower see http://jsperf.com/object-freeze-immutable/2 and http://jsperf.com/object-freeze-immutable/4

I would argue do either freeze all or nothing. But freezing all (static class properties and all created instances) is no option because it is to slow in the most browsers. 

So in my opinion we should leave it like it is and have a pseudo immutability and wait until the performance of Object.freeze improves in the most common javascript runtime engines. Other javascript libraries like Immutable.js don't freeze the objects as well.

But i am curious if there are any other opinions.

**Comment by phueper** [comment]
I think if we can freeze the static properties we should do it ...
but i agree that freezing the the complete instance is  not an option if it influences performance ... 

I think that changing the static value _could_ happen by mistake, e.g. doing `LocalTime.MIDNIGHT = someVar` instead of `LocalTime.MIDNIGHT == someVar`  (yeah, i know, there are linters/checkers that warn about that but still... )  and that could affect calculations everywhere in js-joda where that static property is used and lead to really weird problems... Thus i think we really should protect our constants/statics as much as we can ... 

The returned "immutable" instances are not that critical in my opinion since they should be rather local and accidental modification wouldn't have as much an impact as changing the statics would have

**Comment by pithu** [comment]
To freeze the lib by default might be more restrictive than we want. If all static properties and classes are frozen, it is not possible anymore to add static properties with a plugin. this could be useful for things like adding a special formatter  to the DateTimeFormatters.

What about to put the option to freeze in an external lib/ plugin. with the code in https://github.com/pithu/js-joda/blob/benchmark/freezeIt.js its almost done. we even might find a way to freeze the newly created instances by that way.

something like:
```
require('js-joda-freeze').freezeStatics(); 
require('js-joda-freeze').freezeInstances(); 
```

**Comment by phueper** [comment]
That sounds like a good idea... so the user could decide wether he wants the potentially enhanced security of freezing with the possible performance penalty or not... could be used e.g. to test the code with  freezing but reduce the performance penalty in live code

**Comment by InExtremaRes** [comment]
This is an old issue, but for that same reason, have you tested this again? Maybe now performance is good enough to worth considering this.

Additionally, have you considered defining static properties as non-writable, non-configurable ones?
