### ISSUE TITLE
Attempting to use YYYY or ww with DateTimeFormatter.ofPattern() throws IllegalArgumentException

### ISSUE THREAD

**Issue by binki** [js-joda/js-joda#192]
I’m trying to format a `LocalDate` into a `«weekYear»-«weekYearWeek»` sort of format. In [the documentation for `DateTimeFormatter.ofPattern()`](https://js-joda.github.io/js-joda/esdoc/class/src/format/DateTimeFormatter.js~DateTimeFormatter.html#static-method-ofPattern), it says that the patterns `'YYYY'` and `'ww'` exist and should produce the sorts of values I’m interested in. However, when I actually to use it, `DateTimeFormatter.ofPattern()` explodes from the pattern.

If I am doing something wrong, could the documentation be updated to show how to do this correctly? I tried installing the `js-joda-locale` package as the error requests, but I didn’t think that `YYYY` or `ww` were locale dependent—I’m probably wrong. Also, the `js-joda-locale` package seems kind of empty and unusable.

Thanks.

```diff
diff --git a/test/format/DateTimeFormatterTest.js b/test/format/DateTimeFormatterTest.js
index 3697e29..543fc3d 100644
--- a/test/format/DateTimeFormatterTest.js
+++ b/test/format/DateTimeFormatterTest.js
@@ -9,6 +9,7 @@ import '../_init';
 import { DateTimeFormatter } from '../../src/format/DateTimeFormatter';
 import { ResolverStyle } from '../../src/format/ResolverStyle';
 import { NullPointerException } from '../../src/errors';
+import { LocalDate } from '../../src/LocalDate';

 /* these tests are not copied from threetenbp, but js-joda tests to increase coverage */
 describe('js-joda DateTimeFormatterTest', () => {
@@ -30,5 +31,15 @@ describe('js-joda DateTimeFormatterTest', () => {
                 formatter.withResolverStyle(null);
             }).to.throw(NullPointerException);
         });
+        it.only('should support YYYY', () => {
+            const formatter = DateTimeFormatter.ofPattern('YYYY');
+            const date = LocalDate.of(2017, 1, 1);
+            expect(date.format(formatter)).to.equal('2016');
+        });
+        it.only('should support ww', () => {
+            const formatter = DateTimeFormatter.ofPattern('ww');
+            const date = LocalDate.of(2017, 1, 15);
+            expect(date.format(formatter)).to.equal('02');
+        });
     });
-});
\ No newline at end of file
+});
```

```
ohnobinki@gibby ~/js-joda $ npm test

> js-joda@1.6.1 test /home/ohnobinki/js-joda
> mocha --timeout 5000 --compilers js:babel-core/register ./test/*Test.js ./test/**/*Test.js ./test/**/**/*Test.js ./
test/*Test_mochaOnly.js



(node:23672) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr
 for more info
  js-joda DateTimeFormatterTest
    withResolverStyle
      1) should support YYYY
      2) should support ww


  0 passing (186ms)
  2 failing

  1) js-joda DateTimeFormatterTest
       withResolverStyle
         should support YYYY:
     Pattern using (localized) text not implemented, use js-joda-locale plugin!
  IllegalArgumentException
      at DateTimeFormatterBuilder.appendWeekField (src/format/DateTimeFormatterBuilder.js:828:15)
      at DateTimeFormatterBuilder._parsePattern (src/format/DateTimeFormatterBuilder.js:943:26)
      at DateTimeFormatterBuilder.appendPattern (src/format/DateTimeFormatterBuilder.js:807:14)
      at Function.ofPattern (src/format/DateTimeFormatter.js:257:47)
      at Context.<anonymous> (test/format/DateTimeFormatterTest.js:35:49)

  2) js-joda DateTimeFormatterTest
       withResolverStyle
         should support ww:
     Pattern using (localized) text not implemented, use js-joda-locale plugin!
  IllegalArgumentException
      at DateTimeFormatterBuilder.appendWeekField (src/format/DateTimeFormatterBuilder.js:828:15)
      at DateTimeFormatterBuilder._parsePattern (src/format/DateTimeFormatterBuilder.js:941:26)
      at DateTimeFormatterBuilder.appendPattern (src/format/DateTimeFormatterBuilder.js:807:14)
      at Function.ofPattern (src/format/DateTimeFormatter.js:257:47)
      at Context.<anonymous> (test/format/DateTimeFormatterTest.js:40:49)



```

EDIT: I think I had bad numbers in my broken tests, maybe they are good now? xD

**Comment by phueper** [comment]
Hi @binki 

First of all, thanks for using `js-joda` and for reporting this issue

The problem here is that while the fields `year` (`uuuu`) and `year-of-era` (`yyyy`) are indeed independent of locale, the `week-based-year` (`YYYY`) and `week-of-month` (`ww`) fields *do* depend on the locale: 
year/year-of-era and week-based-year may be off by one (+/-1) in the first or last few days of a year depending on the week boundary, so the last few days of a year may already have the next year as week-based-year and the first few days of a year may still have the week-based-year of the previous year.
The *rules* regarding the week boundaries are locale specific, and since we have split any locale specific logic (for size reasons) into the separate `js-joda-locale` plugin, the exception is being thrown. 
I think the documentation could be clearer regarding this problem, i'll think about how to make this more clear.

Now, regarding `js-joda-locale` the current version in npm (0.0.0) is indeed just an empty "placeholder" ... However, we are literally (hopefully) just hours away from releasing the first working version of js-joda-locale (0.1.0)  to npm ... 
Now beware, this is a first version, it hasn't seen any usage besides its own tests and may have bugs/problems that need to be solved.
If you would be willing to try this first version, i would actually be very happy to provide support as my time permits, because i am very interested in real life usage of js-joda-locale to get some feedback and usage reports :) 
You can have a look at https://github.com/js-joda/js-joda-locale for some information on the usage and the examples provided there and if you find problems it would be great, if you report issues there.

Thanks, Regards, Pattrick

**Comment by binki** [comment]
@phueper Thanks for the response. I think I chose the wrong format fields, then. Is there a way to format using the ISO weekYearYear and ISO weekYearWeek? Those shouldn’t be dependent on locale (if I understand correctly, they’re based on Monday). Or must I manually format such a thing by using the `IsoFields` accessor?

Good job on making progress on the locale stuff, that will be useful!

**Comment by phueper** [comment]
Hi @binki 

Thanks for the response... we found the following code in threeten which i *think* should help you:

```const ISO_WEEK_DATE = new DateTimeFormatterBuilder()
            .parseCaseInsensitive()
            .appendValue(IsoFields.WEEK_BASED_YEAR, 4, 10, SignStyle.EXCEEDS_PAD)
            .appendLiteral("-W")
            .appendValue(IsoFields.WEEK_OF_WEEK_BASED_YEAR, 2)
            .appendLiteral('-')
            .appendValue(ChronoField.DAY_OF_WEEK, 1)
            .optionalStart()
            .appendOffsetId()
            .toFormatter(ResolverStyle.STRICT).withChronology(IsoChronology.INSTANCE)
LocalDate.now().format(ISO_WEEK_DATE) // "2017-W42-3"
LocalDate.parse('2017-01-01').format(ISO_WEEK_DATE) // "2016-W52-7"
```

This is currently missing in js-joda, we will add these, too, but if you can live with manually using this for now, i think it should solve your problem

One caveat though:
parsing this back does currently throw an exception
```
LocalDate.parse("2017-W42-3", ISO_WEEK_DATE) // uncaught Exception 
```

That's something we need to look into as well. But since you didn't ask about parsing in your initial report, i'm not sure, if you actually need it

**Comment by pithu** [comment]
Hint:

if you simple want to extract the ISO week based year or the ISO week you can `get` the specific `IsoField` from the instance:

```
LocalDate.parse('2017-01-01').get(IsoFields.WEEK_OF_WEEK_BASED_YEAR) // 52
LocalDate.parse('2017-01-01').get(IsoFields.WEEK_BASED_YEAR) // 2016
```

**Comment by phueper** [comment]
Hi @binki 

did these infos help you resolve your problem? If yes, i would close this issue.

Regards, Pattrick

**Comment by phueper** [comment]
Since we got no more feedback, i will close this issue now.

Feel free to reopen or comment if you still see this as an issue for you

Regards, Pattrick
