### ISSUE TITLE
Some Zone Ids do not work

### ISSUE THREAD

**Issue by landrys** [js-joda/js-joda#198]
console.log(ZonedDateTime.now(ZoneId.of('America/New_York')).toString());
gives 
throw new _errors.DateTimeException('unsupported ZoneId:' + zoneId);

**Comment by phueper** [comment]
Hi @landrys,

Thanks for reporting this and thanks for using js-joda. 

It seems you have tried using timezones just with "plain" js-joda. We have split the timezone functionality in a separate module: https://github.com/js-joda/js-joda-timezone

Could you please verify that your problem still exists when using js-joda-timezone as described in its README, and if it does exist, report it in the js-joda-timezone github repository?

I will close this issue here, but please feel free to reopen or create there. 

Regards, Pattrick

**Comment by landrys** [comment]
All good now. Thanks for information.
