### ISSUE TITLE
hashCode() on ValueRange is incorrect

### ISSUE THREAD

**Issue by skroll** [js-joda/js-joda#200]
Currently the hashCode for ValueRange is calculated by:

```
const hash = this._minSmallest + this._minLargest << 16 + this._minLargest >> 48 + this._maxSmallest << 32 +
    this._maxSmallest >> 32 + this._maxLargest << 48 + this._maxLargest >> 16;
return (hash ^ (hash >>> 32));
```

However, javascript cannot handle bitwise shifts >= 32, so this always returns 0.

On top of that, this looks like it was ported from the JDK's ValueRange in java.time.temporal, which has an incorrect implementation anyways (up until sometime in October it appears), since the operator precedence of + precedes << and >>, so the shifts are actually incorrect anyways (it needs parentheses).

**Comment by pithu** [comment]
Hi @skroll 

thanks for using js-joda and for reporting.

Your hint is very helpful  to get the bug solved, for license reason we cannot look into the openJDK implementation. js-joda is a port of the [threetenbp project](http://www.threeten.org/threetenbp/) not of the openJDK because of license reasons.

On the other hand i am curious to know what do you need hashCodes for ? 

Until today we didn't spend to much time on hashCode functions. I am quite sure that we always return same hashCodes for equal objects, but i am not sure if the quality is good in terms of collision and uniform distribution. I am not sure if all this bit shifting works for javascript numbers works as expected. And we do not always return hashCode that are less than 2 ^ 32, but also greater values. In some places we implemented the equals method, but not a hashCode method at all.

So it would help to know what you need hashCodes for? 
Should we implement it for all objects? 
Why its required for ValueRange a class we do not event make public ? 
Do you need small integers (immutable.js prefers SMI's) ? 

The answer to this question would help us to decide in what direction we go here.

**Comment by pithu** [comment]
see #103

**Comment by skroll** [comment]
I actually do not need them. I just noticed it when I was looking at js-joda and noticed that `hashCode()` was implemented and thought it was weird in a js lib. Then I noticed the bitwise shifts, and saw the order of operations issue as well as the >= 32 shifts that wouldn't work.

Just figured I would report the issue, in case it would help anyone else.

**Comment by pithu** [comment]
Ok, i fixed the existing hashCode functions, by replacing all functions that use a bitwise shift >= 32 by a common hashCode function as proposed long time ago in Joshua Bloch's book 'effective java'. And all hashCode functions ensure to return a int32 hashCode.

Nevertheless its very questionable if we want to keep the hashCode functions at all. As far as i know there requested by scala.js users and the latest immutable.js supports objects with a hashCode function.

I will close the issue for now. If anyone of you has an opinion about it, please let us know.
