### ISSUE TITLE
[Question] How do I format time?

### ISSUE THREAD

**Issue by nwshane** [js-joda/js-joda#207]
I'm trying to figure out how to format times by hour, minute, second, and am/pm, like in [moment JS](https://momentjs.com/docs/#/displaying/). For example:

```javascript
// pseudocode
LocalTime.of(15, 3, 2).format('h:mm:ss a')
-> "3:03:02 pm"
```

I've had difficulty finding documentation, but I've found [hints](https://github.com/js-joda/js-joda/issues/163) that there is a way to do this. Is it possible to format times with js-joda, and if so how?

**Comment by phueper** [comment]
Hi @nwshane 

sorry for taking so long to answer your question. you can indeed format a time, please have a look at our API docs at https://js-joda.github.io/js-joda/esdoc/, especially class/src/LocalTime.js~LocalTime.html#instance-method-format and https://js-joda.github.io/js-joda/esdoc/class/src/format/DateTimeFormatter.js~DateTimeFormatter.html#static-method-ofPattern 

Regarding your example, i can do this:

```console.log(LocalTime.of(15,3,2).format(DateTimeFormatter.ofPattern('h:mm:ss')))```

which results in `3:03:02` ...regarding am/pm you will *also* have to use the new `js-joda-locale` plugin  found at https://github.com/js-joda/js-joda-locale   ... since am/pm of day are locale specific (the string is different depending on the locale) you will need to use that plugin

Regards, Pattrick

**Comment by nwshane** [comment]
Thanks for the response, @phueper !
