### ISSUE TITLE
flow / TypeScript type annotations / bindings

### ISSUE THREAD

**Issue by phueper** [js-joda/js-joda#23]
It would be nice to have flow and Typescript annotations / bindings to be able to type check the js-joda code itself but also give users the possibility to type check their usage of js-joda...
Even nicer would be if those could be generated from the esdoc comments.
Flow seems to have a way to have inline comments in e.g. function parameters but does not use the docblocks. I haven't checked for typescript yet

**Comment by spencerwi** [comment]
Before seeing this issue, I started writing some to submit to DefinitelyTyped...but there's a _lot_ there and I'm not sure I have the pieces right.

I'll toss what I've got up in a gist so that it'll at least be a good start point in case y'all want to use it.

**Comment by spencerwi** [comment]
Here's the gist: https://gist.github.com/spencerwi/03ac7f4dc1ab093166f0f676f8faa7e1

**Comment by phueper** [comment]
Very cool contribution, thanks a lot! 
Would you mind creating a Pull Request for this? Then we could discuss in the PR if needed and also (credit where credit is due) your name would be on the commit as the author of this contribution. We would then get the file into the distribution so others can use it to typecheck. Also then we could maybe sync this to a commit to DefinitelyTyped so the Type Bindings could stay in sync?

**Comment by jrnail23** [comment]
Along these lines, have y'all considered maybe incrementally rewriting js-joda in TypeScript?
It's a lot more of a natural conversion from Java than pure javascript, and in addition to the typechecking benefits, you'd have TypeScript definitions that would always be up to date.
If you have any interest at all, I'd be interested in pitching in for that effort.

The reason I'm bringing this up is that I'm finding myself depending on the existing typescript definitions to help me get some flowtype defs going for my own work, and I'm finding some things here and there that are either incomplete, or might not translate so well.

**Comment by phueper** [comment]
Hi @jrnail23 

regarding typescript and/or flow, we would like to keep our codebase in "standard" ES6/7/... 
We do provide the typescript .d.ts files and would also provide flowtype definitions, however currently they are manually generated... i would really like to have a "single source of truth" for the interfaces (preferrably in our esdoc comments) and generate the typescript and flowtype definitions from that, but i haven't found an easy way to do that yet...

Having said that... if you come across things that are incomplete or don't work as excpected in the esdoc and/or type definitions, we are very happy to get PRs that fix them or reports what is wrong. As was done by spencerwi and resulted in a PR and then in the current .d.ts files we provide. Also if you have a way to generate flowtype defs from the typescript definitions, i'd be very interested to integrate that.

Regards, Pattrick

**Comment by dgreene1** [comment]
> we would like to keep our codebase in "standard" ES6/7

As far as I know, TypeScript always outputs standard JS if you configure it to do so. In fact, one of their design goals is to never introduce a language feature that the ES committee hasn’t agreed upon. That’s one of the reasons why you can use the existential operator yet (i.e. `optionalVar?.optionalProperty?.someFunction()`) because the operator hasn’t made its way into standard ES yet.

Anyway, so I think there are better arguments against TypeScript.

Personally, I find it to really help development. And as a maintainer of a few open source libraries, it has really helped improve the quality of my real life since I don’t have to worry about contributions as much (since I know that the bulk of the effort has been caught by the compiler).

**Comment by phueper** [comment]
Hi,

yes, Typescript is to my understanding transpiled to plain JS and it has the goal to stay syntactically close to ESx as far as i know.
And one might even argue that it is maybe easier to convert the java threeten code into Typescript than into ES if you would start from the beginning.
However, when we started working on js-joda we decided that we would like to write it in plain ES and at least for me i can say that i still stand by this decision and would like to continue writing code in the "standard" ES.
We are happy to provide the community contributed typescript bindings and we see that they are being used (at least they are improved / changed / issues reported).
Again, for me i can say that i wouldn't want to start over with a port to typescript, i'm quite happy with the code in ES and i still can see that there are things that could be improved in a more ES like style if we ever have time for them.
That being said, there have been ports of the threeten/joda API to other languages (e.g. noda) and i still very much like the API from using it in both Java and JS ... so there might be room for a "ts-joda" ... but it's not something that **i** would currently plan to work on :)

**Comment by dgreene1** [comment]
> Again, for me i can say that i wouldn't want to start over with a port to typescript

Maybe you know this maybe you don’t, but allow me to clarify that you don’t have to port the entire code base. TypeScript allows you to have a codebase that is partially JS and partially TS. So you can migrate file by file.

You can see examples of this with how Jest and VSCode have recently ~ported~ migrated to TS file by file.

> we see that they are being used (at least they are improved / changed / issues reported).

If the code was written in TS then you wouldn’t have issues reported about the types being wrong. So that’s at least one place where it would save time for maintainers.
