### ISSUE TITLE
Compare notes with other threeten projects (Formatting/locale/timezone support)

### ISSUE THREAD

**Issue by soc** [js-joda/js-joda#24]
Hi, I'm from https://github.com/soc/threetenbp!

We are currently investigating how to support the JSR-310 API in the browser, and two missing blocks are formatting with locale support and using a timezone database.

Did you come to any conclusions/solutions yet or are you interested in comparing notes?

Thanks,

Simon

**Comment by phueper** [comment]
Hey, 

Supporting a JSR-310/joda compatible API for JS is exactly the goal of our project.  We also chose the threetenbp as a base for licensing reasons.
Our current plan is to release a first milestone without localization and timezone database support, to have a fully usable library. 
But those would be next steps on the roadmap... I think cooperating would be a great idea!

Regards, Patty

**Comment by soc** [comment]
Ok, cool. Yes, we are also at this stage: Everything (seems to) work except locale/timezone stuff, and with some minor stubs for Locale, that starts working in the browser, too. We already split the codebase for JVM- and browser-specific TZDB support, but haven't provided an implementation for the browser yet.

**Comment by pithu** [comment]
Hi Simon,

sound like a great interesting project. What is the main focus of your project, Scala or Javascript ? You are using Scala.js for Javascript generation, is that correct? How you want to handle the dependencies to the jdk classes like ConcurrentMap, BigDecimal, StringBuilder, etc.? Do you have already a working javascript lib?  A lot of questions come up in my mind, would be very interesting to hear more about your plans.
When we started, we had a similar idea, but then decided to make a 100 percent es2015 lib.

Most annoying issue that we found, are the dependency cycles in the threeten implementation. The dependency cycles are a problem, because of the different way the javascript engine is loading and interpreting the code during startup. Our workaround was to control the way we initialize const instances and at some places we removed cycles by splitting out the code of static factories methods. 

Concerning locales, i guess the best choice is moment-locale. With a little adapter it should be useable without the moment core lib.

Concerning iana timezone db, i just had a short look on it. I am not sure if it is possible to use moment-timezone format here. It has a dependency to the moment core lib as well. That might be solvable by an adapter as well. But not sure if the format is usable for threeten ?.

Regards Philipp

**Comment by soc** [comment]
@pithu Most common JDK classes are supported (scala.js just provides implementations for them), and code works as-is on Scala.js. We currently run the test suite against our implementation only on the JVM backend, but because Scala.js' translation is pretty much perfect, it gives us a lot of confidence that it works the same in the browser (modulo missing formatting/timezone stuff):
https://gist.github.com/soc/a706f372ab864ffb37fa

Scala.js basically tells you if you use classes which are missing in the browser during compilation, but only if you actually use them.

Haven't looked at moment-locale yet, I thought that `Intl` had everything we needed.
Also haven't looked at the actual format used by moment, still need to do that.

Thanks!

**Comment by soc** [comment]
Just looked at https://github.com/moment/moment-timezone/tree/develop/data and the associated packing/unpacking code. I think it looks quite reasonable. I would probably start using that for my project. No need to reinvent this stuff if it already exists!

**Comment by timrwood** [comment]
@soc, you can read up on the data format more here: https://github.com/moment/moment-timezone/pull/82.

We are in the middle of a transition to es6 modules, so you may find https://github.com/moment/moment-timezone/tree/es6/src/unpack and some of the other modules useful.

**Comment by pithu** [comment]
@timrwood great news! sound like we can reuse it for js-joda. we just need to import the [es6/src/unpack](https://github.com/moment/moment-timezone/tree/es6/src/unpack) and a packed data file and then map the unpacked data to org.threeten.bp.zone.StandardZoneRules somehow.

btw: i like the idea  of @mj1856 to pick a earliest year for tzdb data

**Comment by soc** [comment]
@timaschew Nice, thanks!

**Comment by timaschew** [comment]
I think you mean @timrwood

**Comment by soc** [comment]
Ooops, sorry. Yes!

**Comment by soc** [comment]
@timrwood  Nice, thanks!
