### ISSUE TITLE
Parsing ISO8601 DateTime with Time 24:00:00 throws DateTimeParseException

### ISSUE THREAD

**Issue by polmabri** [js-joda/js-joda#249]
According to ISO8601 24:00:00 is valid and denotes midnight at the end of a calendar day:

https://en.wikipedia.org/wiki/ISO_8601#Times

```javascript
LocalDateTime.parse("2018-07-31T24:00:00")
```
throws:
```
DateTimeParseException: Text '2018-07-31T24:00:00' could not be parsed: Invalid int value for HourOfDay: 24: 2018-07-24T24:00:00, at index: 0
```

**Comment by pithu** [comment]
Hi @polmabri, 

thanks for using js-joda and your question. Indeed 24:00:00 is part of the ISO spec and can not be parsed neither by js-joda nor by threeten. 

As far as i know, the reason is because its to hard to implement. See this post for further explanation https://stackoverflow.com/a/5388148.

I will close this issue for now, please feel free to reopen it, if you have further remarks.
