### ISSUE TITLE
consolidate repos / use scoped packages

### ISSUE THREAD

**Issue by phueper** [js-joda/js-joda#273]
The current situation with multiple separate repos for js-joda, js-joda-timezone, js-joda-locale, js-joda-extra, ... is hard to maintain, updates / changes in API are hard to do across repos

Solution: move to monorepo, maybe use lerna to manage the repo 

Also at least for locale we have problems with the npm packages names being too long/too many dashes and hyphens...

We could think about moving to scoped pacakge names, i.e. `@js-joda/core` , `@js-joda/timezone`, `@js-joda/locale`, ... at least for locale this seems to solve the naming problem... and it is something that e.g. babel (`@babel/core`, ...) have also adopted

**Comment by phueper** [comment]
see https://github.com/js-joda/js-joda/tree/monorepo

**Comment by phueper** [comment]
TODOs

- [ ] rename packages to @js-joda/...
- [ ]  structure
- [ ]  build / travis
- [ ]  greenkeeper
- [ ] central packages like eslint, babel, ... to root ? also their configs?
- [ ] docs to root? and build all of them ? 
- [ ]  how to publish?? (if the locale subpackages are also lerna packages, maybe we can `lerna publish` ??

**Comment by pithu** [comment]
I am about to switch to the mono repo version. Here is a short documentation what i have done so far:

Because there where so many change from master branches compare to the monorepo branch, i decided to create a new monorepo branch (monorepo-pithu) from all master branches and then merge @phueper monorepo branch changes manually into the new branch.

I have done that by creating in the repos locale, timezone, extra and examples a branch `monorepo-pithu` and then `git move` all files to `packages/[reponame]`. In the js-joda repo i did the same and then adding the other repos as `git remotes`, and then merge these changes into js-joda#monorepo-pithu branch. After that i manually merge the changes from the @phueper monorepo branch.

I skipped greenkeeper for now.

After fixing the last issues, i will merge the monorepo-pithu branch into master and mark all other repos as deprecated.

The bullet-points in the comment above will be still open, we have to fix them afterwards, step by step.

**Comment by phueper** [comment]
great! go, go, go @pithu!

**Comment by pithu** [comment]
Done, js-joda is a monorepo now! Most issues fixed.

**Comment by phueper** [comment]
@pithu can this be closed?  i think we should close it and if we feel the need to fix the missing points from the checklist we could create extra issues for them?

**Comment by phueper** [comment]
we decided to close this issue... one followup created for the publishing to npm, the other open points could be adressed in separate issues if we feel the need for them
