### ISSUE TITLE
How to add a chronology

### ISSUE THREAD

**Issue by joakim** [js-joda/js-joda#310]
First of all, thank you for bringing Joda to JS!

I would like to add support for the Persian calendar by porting the code from [this fork of Joda-Time](https://zubinkavarana.github.io/joda-time/). How would I go about doing this?

In Joda-Time, one could pass an instance of the [Chronology class](http://joda-time.sourceforge.net/apidocs/org/joda/time/Chronology.html) to the constructor:
```
LocalDate date = new LocalDate(PersianChronology.getInstance());
```

This doesn't appear to be possible in the threeten backport and js-joda, although chronology is still used under the hood (`IsoChronology`).

Do I have to fork js-joda? Or could it be done by writing a stand-alone JavaScript module that depends on js-joda and provides copies of `LocalDate`, `LocalTime`, etc, using my `CustomChronology` instead of `IsoChronology`?

Edit: This is issue #310 🎉

**Comment by pithu** [comment]
Hello @joakim,

we welcome this idea very much, perfect fir for #310 ;)

I took a brief look at it and that's the rough plan that come to my mind:

- First of all, `js-joda` is a port of the `threeten` API not from `joda-time`. So the `joda-time` classes can help as an orientation, but since concepts changed a lot between these APIs, there are not a blueprint.
- You can find the implementation for threeten calendars in the [threeten-extra package](https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/chrono/package-summary.html), therefore `js-joda` calendars should go to [js-joda-extra](https://github.com/js-joda/js-joda-extra)
- Unfortunately the Persian calendar is missing in threeten-extra, but i would expect that the concepts are very similar to the other calendar.
- It would be the first calendar in `js-joda-extra`, so there might be some foundation missing, that have to be implemented.

I hope that helps a bit.

**Comment by pithu** [comment]
I close it for now, feel free to reopen it or even better, place a PR
