### ISSUE TITLE
Expose library in documentation

### ISSUE THREAD

**Issue by hpurmann** [js-joda/js-joda#338]
Is there some kind of playground for js-joda?

Most libraries (e.g. lodash) expose their library as a global variable on the documentation page, so that one can easily try the library in the dev tools.

**Comment by pithu** [comment]
Unfortunately not anymore on our github page, since we generate the page with esdoc. Nevertheless there is:
- a js-fiddle mentioned in the docs (https://js-joda.github.io/js-joda/manual/getting-started.html#jsfiddle) and
- the lib is exposed as a global variables on our toplevel github page https://js-joda.github.io/. so there you can play

**Comment by hpurmann** [comment]
Perfect, thank you Philipp!
