### ISSUE TITLE
DateTimeFormatter returns wrong year for specific date

### ISSUE THREAD

**Issue by prinzdezibel** [js-joda/js-joda#340]
Formatting a local date that represents an event in the year of the Lord will result in a wrong year displayed.

```
import { DateTimeFormatter, LocalDate } from 'js-joda';

const numericDateFormatter = DateTimeFormatter.ofPattern('yyyy/MM/dd');
numericDateFormatter.format(new LocalDate(0,2,8));

'0001/02/08'

```

**Comment by phueper** [comment]
Hi @prinzdezibel 

Thanks for using js-joda and thanks for reporting.. I cannot test this right now, but I think the output is correct, you are not outputting the epoch, but proleptic year 0 is actually year 1 BC... More Infos are eg here https://stackoverflow.com/questions/29014225/what-is-the-difference-between-year-and-year-of-era. For the proleptic year, please use uuuu instead of yyyy
I will close this issue, feel free to reopen in case I couldn't clarify it

Best Regards, Pattrick
