### ISSUE TITLE
Tree shaking / dead code elimination is not working in Webpack/Rollup

### ISSUE THREAD

**Issue by slavafomin** [js-joda/js-joda#365]
Hello!

Thank you for this great library!

However, I was trying to use it in my Angular project and have found myself in a situation, where `js-joda` package is not getting tree shaken, instead the entire library is getting added to the application's bundle.

This seems strange to me, because from the looks of it, it should work: you are providing a correctly looking FESM module and reference it with the `module` field in the package manifest.

After fixing #214 have you actually tried to build it with tree shaking?

I've created a demo repository to help you reproduce the issue with both Webpack and Rollup:
https://github.com/slavafomin/js-joda-tree-shake

Also, you should add `sideEffects: false` field to the package manifest in order to signify that library doesn't contain modules with side effects (it isn't right?). However, it looks like it won't fix the issue.

Do you have any ideas? Thank you.

**Comment by slavafomin** [comment]
After looking at the code in the repo I see a lot of circular dependencies. I'm not sure, but I guess it could be related to the issue. Circular dependencies are considered an anti-pattern in software development (not without good reasons). Do you think it would be possible to restructure the classes to avoid such dependencies?

**Comment by pithu** [comment]
Hello @slavafomin 

I did not get deep into the tree shaking issue, but as far as i remember you bring it already to the point: Because of the circular dependencies, tree shaking cant remove a lot of code from `js-joda`.

Actually, when porting threeten to javascript, the biggest pain point where the circular dependencies of the project. Not only because i am an advocate of the `Acyclic Dependencies Principle` (and the component principles in general), but furthermore because its actually quite painful, almost impossible to model circular dependencies in javascript (because the pre-compile step as in java is missing in javascript). So we had to make a lot of dirty tricks, to get this work.

Of course we thought about removing the cycles, but we did not find an appropriate way to do it. The problem is somehow based in the nature of this library. You can convert any date-time class  into any other date-time class. Like you can do the complete circle through the main date-time domains:
`LocalDate.now().atStartOfDay().atZone(zonedId).toInstant().atZone(yourZoneId).toLocalDate()`
And therefore you have the cyclic imports in any of those classes.

But of course we are very open for ideas, to get rid of that problem.

**Comment by slavafomin** [comment]
@pithu thank you for explaining this. I'm not sure if this is a too radical idea, but maybe the API should change in the future to make the library more suitable for the language and the build tools. However, I doesn't have enough knowledge of the library itself to propose such changes.

The other idea would be to split functionality into independent modules that would augment existing classes when included. This would produce side-effects, but it would allow to split the library and load only needed parts. I believe RxJS used this approach at some point. However, in my opinion, I would stick to the first approach if possible.

**Comment by phueper** [comment]
@slavafomin well... The whole point of this library is to provide a js version of the API of the threetenbp / joda library from java, that we and seemingly many others consider a quite nicely usable api for date/time handling... 
So changing the api is something that we probably will not consider easily...

And splitting is already done... The js-joda module is what we consider the core of the library, there is also the timezone, locale, extra parts which were in our opinion obvious and nicely usable splits while still keeping the core usable and at a reasonable size... 

I guess we'd be happy to discuss further possible splits but they would need to be considered so the library remains usable without too much hassle. 

And frankly they don't seem to jump at me, otherwise we'd have maybe already considered doing them... But as I said we'll be happy to get proposals and certainly consider and discuss them. 

Regards, Pattrick

**Comment by henryw374** [comment]
Hi folks, 

Here is a demo project which compiles some end user code using js-joda with the [Closure compiler](https://developers.google.com/closure/compiler/). You can see the output file from the compilation has eliminated much of js-joda - the output file is 3.9k - about 10x smaller than the full minified js-joda.

FYI The Closure compiler is used by the [Clojurescript](https://clojurescript.org/) compiler, hence why this is interesting to me since I maintain a cross-platform java+js time library, which uses js-joda: https://github.com/henryw374/cljc.java-time

I'm not that familiar with Closure compiler, but from my experiments so far, it is only able to eliminate js-joda in it's original source form. If I give it the output of the umd or esm builds from rollup, it gets confused and includes everything. 

Even though it has eliminated most of js-joda in the output, it still includes a few functions that the end user is not calling, (these are adjuster related, 'get' and 'query') so I am still experimenting to see if any changes can be made to the source to eliminate those in the output as well.

**Comment by pauldraper** [comment]
> But of course we are very open for ideas, to get rid of that problem.

The solution is virtually always to move member functions to top-level functions.

E.g. replace

```js
LocalDate.now().atStartOfDay()
```

with

```js
atStartOfDay(LocalDate.now())
```

It's "uglier" but this is the solution to tree shaking (and cycles).

**Comment by henryw374** [comment]
@pauldraper is there a way to do this and keep in sync with the java.time API though? if not, I would guess it would be a major re-write, effectively a new library.

**Comment by henryw374** [comment]
Separately, in case anyone is keen to take it on I started work on removing the `init` function from js-joda - basically trying to make the lib amenable to static analysis https://github.com/js-joda/js-joda/pull/463
