### ISSUE TITLE
support OffsetDateTime

### ISSUE THREAD

**Issue by xenoterracide** [js-joda/js-joda#432]
https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html

**Comment by pithu** [comment]
dito see #434

**Comment by xenoterracide** [comment]
I don't know what I was thinking with year... but this doesn't work

```
import { OffsetDateTime, ZonedDateTime, convert } from '@js-joda/core';
```

and `OffsetDateTime` isn't mentioned in the documentation https://www.npmjs.com/package/@js-joda/core

**Comment by pithu** [comment]
Hi @xenoterracide 

thanks for reporting the documentation issue. i just rebuild the esdoc, at least in the the [api reference](https://js-joda.github.io/js-joda/identifiers.html) it is documented now.  
About mentioning it in the README.md, we are open for PR's ;)

For the typescript issue: 
Indeed, `OffsetDateTime` and `OffsetTime` are still missing in the typescript definition file because there added just in the latest release and nobody in the typescript community updated it yet. Again we are open for PR's. Sorry to say that, but the the typescript definition are completely driven by the community not by us, the maintainers.

**Comment by xenoterracide** [comment]
> Sorry to say that, but the the typescript definition are completely driven by the community not by us, the maintainers.

unfortunate, and surprising, given inspiration I would have expected js-joda to be written in typescript
