### ISSUE TITLE
ChronoUnit.MICROS math operations are in nanoseconds, resulting in a limited range of times due to JavaScript limitations

### ISSUE THREAD

**Issue by ziggythehamster** [js-joda/js-joda#472]
ChronoUnit.MICROS is expressed in terms of nanoseconds, which means that this raises an arithmetic error even though it need not:

```javascript
ChronoUnit.MICROS.between(Instant.EPOCH, Instant.parse('2021-02-18T13:12:00.123456Z'));
```

If you take it upon yourself to do the math, it works as you'd expect:

```javascript
(ChronoUnit.SECONDS.between(Instant.EPOCH, timestamp) * 1000000) + timestamp.get(ChronoField.MICRO_OF_SECOND);
```

**Comment by pithu** [comment]
Hi @ziggythehamster 

thanks for using js-joda and reporting this issue.

JavaScript uses floating point numbers and can only safely represent integers that are in the range of `Numbers. MAX_SAFE_INTEGER` <= x <= `Numbers. MAX_SAFE_INTEGER` (9007199254740991). Therefore we had to limit js-joda to numbers within the range of safe integer values . Anything greater ger than that, will throw an exception. Actually this should be only a problem for nanoseconds, since we limit all other entities to not exceed that limit eq `Year.MAX_VALUE` is `999999` and can be represent within Numbers. MAX_SAFE_INTEGER seconds.

The problem dealing with greater numbers is that there are leading to unexpected results, eq `16136539200000000 + 1 === 16136539200000000` or `ChronoUnit.MICROS.between(Instant.EPOCH, Instant.parse('2021-02-18T13:12:00.123456Z'))` would be equal to `ChronoUnit.MICROS.between(Instant.EPOCH, Instant.parse('2021-02-18T13:12:00.123457Z'))` 

I hope that helps.

**Comment by ziggythehamster** [comment]
I'm well aware that you can't exceed `MAX_SAFE_INTEGER`, without introducing float rounding issues. `MAX_SAFE_INTEGER` microseconds since the Unix epoch occurs at Tuesday, June 5, 2255 11:47:34.740 PM UTC.

There should be no math issues involved in calculating the number of microseconds since the epoch for any dates occurring in any of our lifetimes. However, because ChronoUnit.MICROS is defined as 1000 nanoseconds, all subsequent math for between happens in nanoseconds. `MAX_SAFE_INTEGER` nanoseconds since the Unix epoch is Wednesday, April 15th, 1970 5:59:59.254740991 AM UTC. Obviously that one cannot work, but microseconds clearly can _if_ the library is doing math in microseconds, not nanoseconds.

Whatever the library is currently doing is incorrect. Either the math code needs to know it can safely take out a factor of 1000 (nanos->micros) for a micro unit when doing math on it, or micros need to be defined as 1 microsecond instead of 1000 nanoseconds.

I can confirm that .plus() works:

```javascript
Instant.EPOCH.plus(micros, ChronoUnit.MICROS).toString(); // correct result
```

Maybe it's just .between() that is wrong. I'm not certain. The code I posted in my original comment shows that I can safely scale it myself and then add MICRO_OF_SECOND to get the correct result, and for all dates in the next couple hundred years, I don't exceed `MAX_SAFE_INTEGER`.

**Comment by pithu** [comment]
The high level explanations is: 

js-joda is a port of java threeten api, that is using java long 64 bit signed int values. In js-joda we have to limit ranges to 53 bit range, eg duration in nanos is limited to about 100 days. There are obviously some cases where we reach this limit early as expected in js-joda, because the calculation is not optimized to javascript. 

Equal in your case, js-joda is is using internally nanos for calculation, that's the reason why it's limited to `Number.MAX_SAFE_INTEGER / LocalTime.NANOS_PER_DAY` days. This special case can be probably fixed and extend the limit to about  300 years. Shouldn't be to difficult, maybe i find some time to optimize this, but i can't promise.

**Comment by pithu** [comment]
Hi @ziggythehamster i found some time to work on a PR for this issue. Could you check the PR, does it fix your problem ?

**Comment by ziggythehamster** [comment]
It appears to (I don't know how to grab a build from that branch and test my code, though - maybe it's just a matter of pointing package.json at github, but the packaging split might make it more complicated than that). I don't know if you typically test exceptions, but it might be a good idea to make the 200 year test assert that trying nanos throws an error.
