### ISSUE TITLE
ZoneIdFactory is missing from exports on Node 4.x

### ISSUE THREAD

**Issue by veselov** [js-joda/js-joda#65]
Hi.

I'm trying to use Joda in Node 4.x (4.4.5)
For some reason, some classes (including ZoneIdFactory) are missing from the module object.
I can't quite see why, though.

    > require('js-joda').ZoneIdFactory
    undefined

I can't import it from the source dir because of ES6 syntax.

May be compiled dist doesn't go over all the classes?

Thank you :)

**Comment by pithu** [comment]
Hi @veselov, 

only the classes listed in src/js-joda.js are exported and public.

The class ZoneIdFactory is a private helper class only. The class is not even part of the threeten API, Its just a workaround for some javascript issues. 

All methods of ZoneIdFactory are added to the class ZoneId, as mentioned in the docu. So please use the exported class ZoneId instead of ZoneIdFactory. 

pithu
