### ISSUE TITLE
No mention of Instant in manual - intended?

### ISSUE THREAD

**Issue by rmunn** [js-joda/js-joda#685]
The [manual](https://js-joda.github.io/js-joda/manual/) has entries for LocalDate, LocalTime, LocalDateTime, ZonedDateTime, Period, and Duration, but no entry for Instant. This seems like a strange omission, as Instant is the most appropriate type for representing timestamps in a log file (a rather common use-case). There's good documentation at https://js-joda.github.io/js-joda/class/packages/core/src/Instant.js~Instant.html — why not copy that introductory material into a `docs/manual/Instant.html` file? Or is the omission of Instant from the manual actually deliberate?

**Comment by pithu** [comment]
Hi @rmunn, thanks for bringing up this issue. Its not intended, its more because of historical reasons, we started with a one page cheat sheet and someone break it into several sub pages with several topics. But the idea is still having a cheat sheet style, so just copying the documentation reference of Instant is not what i would expect here. But we are open for PR, that adds an extra Instant item, with some examples how to use Instant.
