### ISSUE TITLE
apparent rounding error in parse

### ISSUE THREAD

**Issue by dgreene1** [js-joda/js-joda#691]
Please let me know if this is enough detail. It is reproduceable in the console of https://js-joda.github.io/js-joda/ in latest Chrome.

Note, there is no Feb 31st and there is no April 31st in 2023.

Actual Results:

```ts
LocalDate.parse('02/31/2023', DateTimeFormatter.ofPattern('M/d/y'))
// e {_year: 2023, _month: 2, _day: 28}

LocalDate.parse('03/31/2023', DateTimeFormatter.ofPattern('M/d/y'))
// e {_year: 2023, _month: 3, _day: 31}

LocalDate.parse('04/31/2023', DateTimeFormatter.ofPattern('M/d/y'))
// e {_year: 2023, _month: 4, _day: 30}
```

Expected Results:

```ts
LocalDate.parse('02/31/2023', DateTimeFormatter.ofPattern('M/d/y'))
// ERROR should be thrown

LocalDate.parse('03/31/2023', DateTimeFormatter.ofPattern('M/d/y'))
// e {_year: 2023, _month: 3, _day: 31}

LocalDate.parse('04/31/2023', DateTimeFormatter.ofPattern('M/d/y'))
// ERROR should be thrown
```

**Comment by pithu** [comment]
The actual results are expected and the same as in upstream projects threetenbp and java.time. Maybe someone in the java community can answer this issue.

**Comment by mellis481** [comment]
> The actual results are expected.

@pithu Can you elaborate on your assertion that the expected behavior for parsing a date string representing a non-existent date would 1. successfully parse 2. resolves to a date that doesn't match the entered date parts from the string?

**Comment by dgreene1** [comment]
At best, I think this issue should be converted into a documentation update so that the formatting/parsing page of the documentation explains that you need to:

1. replace `yyyy` with `uuuu`
2. use `withResolverStyle(ResolverStyle.STRICT)` 

That looks like:

```ts
const localDateParseStrict = ({dateStr, pattern}: {dateStr: string, pattern: string}): LocalDate => {
    const replacedPattern = pattern.replace(/y/g, "u");
    const formatter = DateTimeFormatter.ofPattern(replacedPattern).withResolverStyle(ResolverStyle.STRICT);

    return LocalDate.parse(dateStr, formatter)
}

const goodOutput = localDateParseStrict({dateStr: '2/28/2018',pattern: "M/d/yyyy"}); 
console.log(`goodOutput is: ${goodOutput}`); // e {_year: 2018, _month: 2, _day: 28}

const shouldThrowBeforeAssigning = localDateParseStrict({dateStr: '2/31/2018',pattern: "M/d/yyyy"});
console.log(`shouldThrowBeforeAssigning is: ${shouldThrowBeforeAssigning}`); // never will be called
```

I would ask @pithu to allow us to add this `localDateParseStrict` function, but I recall his earlier insistence on keeping an exact API of threeten. So instead, I'm requesting you allow me to update the documentation.

**Comment by pithu** [comment]
@dgreene1 thanks for giving some more Details. Exactly, with the ResolverStyle you can control the behavior of the formatter during the resolving phase, see https://js-joda.github.io/js-joda/class/packages/core/src/format/ResolverStyle.js~ResolverStyle.html

In your case, you can get the expected results by using STRICT mode:

```
LocalDate.parse('02/31/2023', DateTimeFormatter.ofPattern('M/d/u').withResolverStyle(ResolverStyle.LENIENT))
// '2023-03-03'
LocalDate.parse('02/31/2023', DateTimeFormatter.ofPattern('M/d/u').withResolverStyle(ResolverStyle.SMART))
// '2023-02-28'
LocalDate.parse('02/31/2023', DateTimeFormatter.ofPattern('M/d/u').withResolverStyle(ResolverStyle.STRICT))
// throws
LocalDate.parse('02/01/2023', DateTimeFormatter.ofPattern('M/d/u').withResolverStyle(ResolverStyle.STRICT))
// '2023-03-01'
```
Be aware that STRICT mode is more picky about formatter patterns, in your case use `u` instead of `y` as year pattern.

@dgreene1 PR's improving documentation are always welcome.

Regarding adding a `localDateParseStrict` function: IMO its too specific for a certain use-case, date domain and pattern. I would see the risk adding more and more functions for a lot of specific uses cases with ambiguous names. It would be contrary to the immutable, composable and expressive syntax of the threeten API.
